version: "3.8"

networks:
  vaxlocator:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.22.0.1/24

services:
  postgres:
    image: postgres:latest
    container_name: "vaxlocator"
    environment:
      - POSTGRES_USER=vaxlocator
      - POSTGRES_PASSWORD=vaxlocator
      - POSTGRES_DB=openup-vaxlocatordb
    ports:
      - "5432:5432"
    volumes:
      - vaxlocator-pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "vaxlocator"]
      interval: 30s
      timeout: 10s
      retries: 3
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: 256M
        reservations:
          cpus: "0.1"
          memory: 128M
    networks:
      vaxlocator:
        ipv4_address: 172.22.0.2
    command:
      [
        "postgres",
        "-c",
        "max_connections=300",
        "-c",
        "shared_buffers=512MB",
        "-c",
        "effective_cache_size=1GB",
        "-c",
        "maintenance_work_mem=512MB",
        "-c",
        "checkpoint_completion_target=0.9",
        "-c",
        "wal_buffers=16MB",
        "-c",
        "default_statistics_target=500",
        "-c",
        "random_page_cost=1.1",
        "-c",
        "effective_io_concurrency=200",
        "-c",
        "work_mem=64MB",
        "-c",
        "min_wal_size=1GB",
        "-c",
        "max_wal_size=2GB",
        "-c",
        "max_worker_processes=4",
        "-c",
        "max_parallel_workers=4",
        "-c",
        "max_parallel_workers_per_gather=2",
      ]

volumes:
  vaxlocator-pgdata:
    driver: local
